// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBpnspX8eFqu8dmAi3wcEeM0aNYLmjtw',
    appId: '1:836077975383:web:793ad37667d6207648b012',
    messagingSenderId: '836077975383',
    projectId: 'pawsitive-6323c',
    authDomain: 'pawsitive-6323c.firebaseapp.com',
    storageBucket: 'pawsitive-6323c.appspot.com',
    measurementId: 'G-VZZT1SYJ97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaq_vRlaZqQjSQK6nazKt30t8doMhLwoY',
    appId: '1:836077975383:android:48d5d8c7aa18fe0348b012',
    messagingSenderId: '836077975383',
    projectId: 'pawsitive-6323c',
    storageBucket: 'pawsitive-6323c.appspot.com',
  );
}
